### PR TITLE
Make search engine link configurable, so I can easily make benchmark

### PR DESCRIPTION
**Pull request by WindSoilder**

### CODE REVIEW

**Comment by dzervas** [comment]
Wouldn't it be better to add some kind of templating in the URL? instead of `"https://" + bing_url + "/search?q=" + query` have something like `engine_url.template(query)` where `engine_url = "https://bing.com/search?q={}"` and `.template` is an imaginary templating function (like python's `.format`)

**Comment by WindSoilder** [comment]
> Wouldn't it be better to add some kind of templating in the URL? instead of `"https://" + bing_url + "/search?q=" + query` have something like `format!(engine_url, query)` where `engine_url = "https://bing.com/search?q={}"`

Do you mean that I can make the `https://bing.com/search` rather than `bing.com` into my configuration file?

I'm afraid it's not friendly for users who wants to make some configuration(Maybe there are no case for it).   In your solution, I have to make a configuration file like this:
```toml
[engine_domain]
duckduckgo = "http://duckduckgo.com/html?t=hj&ia=web&q="
bing = "http://www.bing.com/search?q="
google = "http://www.google.com/search?q="
```
or this:
```toml
[engine_domain]
duckduckgo = "http://duckduckgo.com/html"
bing = "http://www.bing.com/search"
google = "http://www.google.com/search"
```

User need more information about the `scheme`, and `path`, which is unnecessary.

**Comment by dzervas** [comment]
well you're not wrong about that, but which user is going to change the google url anyway

**Comment by WindSoilder** [comment]
There is another issue which need to be concerned:
If I make configuration like this:
```toml
[engine_domain]
duckduckgo = "http://duckduckgo.com/html"
```
What's the default value for this?  `http://....` or `https://...` ? I would like to keep `use_https` argument work in `get_query_url` function.  And it may makes code harder to understand..

**Comment by WindSoilder** [comment]
Merge this for now, please fire a PR if there are better solutions for the code.

**Pull request merged**
