### PR TITLE
more firendly colorize output.

### PR DESCRIPTION
**Pull request by WindSoilder**
Fixes: #71

Hi, @dzervas . I have create this PR to solve the issue in another (maybe fool) way.

The ideal way is your approach in #72 .  But I fell into trouble to take out relative `class` attribute.  

And I think sort tags by *popular languages priority* can help us take a better `syntaxer`. Would you please have a look?

### CODE REVIEW

**Comment by dzervas** [comment]
Oh ok, I'm from mobile, I'll check later.

I was thinking that `SyntaxSet` can recognize a lang by text (`find_syntax_by_text` or something) and should be very close to what SO does. We can keep the tag thing though, if the above fails (or is too far off? What happens if the question has a python tag and the answer is in brainfuck?)

**Comment by dzervas** [comment]
Oh just so your comment on #72... Yeap, this implementation is what I was thinking as well if all the other magic didn't work...

**Comment by WindSoilder** [comment]
> I was thinking that `SyntaxSet` can recognize a lang by text (`find_syntax_by_text` or something) and should be very close to what SO does. We can keep the tag thing though, if the above fails (or is too far off? What happens if the question has a python tag and the answer is in brainfuck?)

Yeah, I'm also try to find something like `find_syntax_by_text` in [doc](https://docs.rs/syntect/4.3.0/syntect/parsing/struct.SyntaxSet.html), but failed.

> What happens if the question has a python tag and the answer is in brainfuck?
Actually when we get syntax from question tag, we can't avoid this scenario :-(

**Comment by WindSoilder** [comment]
@dzervas more thought on this? i think we can use this approach for now.  And try to research for a better way

**Pull request merged**
